# Generated by Django 2.1 on 2020-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0002_auto_20200331_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wordsentiment',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
