# Generated by Django 2.1 on 2020-03-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proto.Attraction'),
        ),
    ]
