# Generated by Django 3.0.5 on 2020-04-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0006_auto_20200331_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proto.Attraction'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
