# Generated by Django 3.0.5 on 2020-06-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0016_auto_20200605_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='travelertype_business',
            new_name='travelertype',
        ),
        migrations.RemoveField(
            model_name='review',
            name='travelertype_couple',
        ),
        migrations.RemoveField(
            model_name='review',
            name='travelertype_family',
        ),
        migrations.RemoveField(
            model_name='review',
            name='travelertype_friend',
        ),
        migrations.RemoveField(
            model_name='review',
            name='travelertype_solo',
        ),
    ]
