# Generated by Django 3.0.6 on 2020-06-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0021_attraction_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_pk', models.PositiveIntegerField()),
                ('dist', models.PositiveIntegerField(null=True)),
                ('direction', models.CharField(max_length=1500, null=True)),
                ('start_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proto.Attraction')),
            ],
        ),
    ]
