# Generated by Django 3.0.6 on 2020-06-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0022_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='dist',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
