# Generated by Django 3.0.6 on 2020-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0025_auto_20200615_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.CharField(default='[]', max_length=150),
        ),
    ]
