# Generated by Django 2.1 on 2020-03-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0004_auto_20200331_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1500)),
                ('date', models.DateField(null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proto.Attraction')),
            ],
        ),
    ]
