# Generated by Django 3.0.5 on 2020-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0014_auto_20200425_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
