# Generated by Django 3.0.5 on 2020-06-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0017_auto_20200606_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
