# Generated by Django 3.0.6 on 2020-06-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0020_attraction_review_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='cluster',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
