# Generated by Django 3.0.6 on 2020-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0023_auto_20200612_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='star_rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
